#!/bin/bash

CONTAINER_NAME="orca-dev"
IMAGE_NAME="fatih"
WORKDIR="$(pwd)/GPU-MPC"

# Check if container exists
if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
    echo "Starting existing container..."
    docker start -ai $CONTAINER_NAME
else
    echo "Creating new container..."
    docker run --name $CONTAINER_NAME \
        --gpus all \
        --privileged \
        --network host \
        -v "$WORKDIR":/workspace \
        -it $IMAGE_NAME /bin/bash
fi