#!/usr/bin/env bash
# Drives the real Figure 2 Ring-LPN OLE engine from SPFSS keys generated by the
# TWO-PROCESS dealerless protocol, replacing the centralized GPU keygen that is
# the pipeline's remaining oracle boundary.
#
# Three stages:
#   1. run the OLE bench once with RINGLPN_OLE_EXPORT_NOISE, which writes each
#      party's private sparse noise for every limb (the benchmark still samples
#      the noise itself; that is a labelled benchmark step, not a distributed
#      sampler);
#   2. for each limb run two independent OS processes of
#      test_two_party_spfss_keygen over TCP with real OT; each reads only its own
#      noise record and writes only its own SPFSS key file;
#   3. re-run the OLE bench with RINGLPN_OLE_SPFSS_KEYS so the engine loads those
#      dealerless keys, and require its own validation to pass.
#
# Outputs:
#   results/ole/ole_two_party_keys_<tag>.csv        (bench rows, dealerless keys)
#   results/ole/ole_two_party_keygen_<tag>.csv      (keygen transcript rows)
#   results/ole/ole_two_party_keys_<tag>.log
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"
BENCH="$ROOT/bin/bench_ole_ringlpn_cuda"
KEYGEN="$ROOT/host_bin/test_two_party_spfss_keygen"
OUTDIR="$ROOT/results/ole"
WORKDIR="${WORKDIR:-$OUTDIR/two_party_keys}"
N="${N:-8192}"
C="${C:-2}"
T="${T:-8}"
QBITS="${QBITS:-64}"
NOISE="${NOISE:-uniform}"
SEED="${SEED:-1}"
ITERS="${ITERS:-1}"
WARMUP="${WARMUP:-0}"
BASE_PORT="${BASE_PORT:-45600}"
TAG="q${QBITS}_${NOISE}_c${C}_t${T}_n${N}"
CSV="$OUTDIR/ole_two_party_keys_${TAG}.csv"
KCSV="$OUTDIR/ole_two_party_keygen_${TAG}.csv"
LOG="$OUTDIR/ole_two_party_keys_${TAG}.log"
CUDA_ARCH="${CUDA_ARCH:-${GPU_ARCH:-89}}"
NVCC="${NVCC:-nvcc}"

if ! command -v "$NVCC" >/dev/null 2>&1; then
  echo "[ole-two-party] nvcc not found; run inside the CUDA environment"
  exit 1
fi

mkdir -p "$OUTDIR" "$WORKDIR" "$ROOT/host_bin" "$ROOT/bin"
: > "$LOG"
rm -f "$CSV" "$KCSV"
# Stale noise/key files from another configuration would be miscounted as extra
# limbs and could even let stage 3 load keys it did not just generate.
rm -f "$WORKDIR"/noise_limb*.noise "$WORKDIR"/keys_limb*.spfss
g++ -std=c++17 -O2 -Wall -Wextra -maes -msse4.1 -mpclmul -mavx2 -mrdseed \
  -I "$PROJECT_ROOT/../SCI/src" -I "$ROOT/src" \
  "$ROOT/src/test_two_party_spfss_keygen.cpp" "$ROOT/src/spfss_host.cpp" \
  -o "$KEYGEN" -lcrypto -lssl -pthread
"$ROOT/scripts/build_ole_cuda_bench.sh" >> "$LOG" 2>&1

bench_args=(--n "$N" --c "$C" --t "$T" --qbits "$QBITS" --noise "$NOISE"
            --seed "$SEED" --iters "$ITERS" --warmup "$WARMUP")

echo "[ole-two-party] stage 1: export per-party noise" | tee -a "$LOG"
RINGLPN_OLE_EXPORT_NOISE="$WORKDIR/noise" "$BENCH" "${bench_args[@]}" \
  --csv-header >> "$LOG" 2>&1

limbs=$(ls "$WORKDIR"/noise_limb*_p0.noise | wc -l)
echo "[ole-two-party] stage 2: dealerless SPFSS keygen for $limbs limb(s)" | tee -a "$LOG"
port=$BASE_PORT
header=1
status=0
for ((limb = 0; limb < limbs; ++limb)); do
  hdr=()
  if [[ $header -eq 1 ]]; then hdr=(--csv-header); header=0; fi
  "$KEYGEN" --party 0 --port "$port" \
            --noise "$WORKDIR/noise_limb${limb}_p0.noise" \
            --out "$WORKDIR/keys_limb${limb}_p0.spfss" "${hdr[@]}" \
            >> "$KCSV" 2>> "$LOG" &
  p0=$!
  sleep 0.2
  "$KEYGEN" --party 1 --host 127.0.0.1 --port "$port" \
            --noise "$WORKDIR/noise_limb${limb}_p1.noise" \
            --out "$WORKDIR/keys_limb${limb}_p1.spfss" \
            >> "$KCSV" 2>> "$LOG" &
  p1=$!
  rc0=0; rc1=0
  wait "$p0" || rc0=$?
  wait "$p1" || rc1=$?
  if [[ $rc0 -ne 0 || $rc1 -ne 0 ]]; then
    echo "[ole-two-party] keygen FAILED (p0=$rc0 p1=$rc1) limb $limb" | tee -a "$LOG"
    status=1
  fi
  port=$((port + 4))
done

echo "[ole-two-party] stage 3: real OLE engine on dealerless keys" | tee -a "$LOG"
if ! RINGLPN_OLE_SPFSS_KEYS="$WORKDIR/keys" "$BENCH" "${bench_args[@]}" \
      --csv-header > "$CSV" 2>> "$LOG"; then
  echo "[ole-two-party] bench FAILED on dealerless keys" | tee -a "$LOG"
  status=1
fi
cat "$CSV" >> "$LOG"

echo "wrote $CSV"
echo "wrote $KCSV"
echo "wrote $LOG"
if [[ $status -ne 0 ]] || grep -qi "fail" "$CSV" || grep -qi "FAIL" "$KCSV"; then
  echo "[ole-two-party] FAILURES present"
  exit 1
fi
if ! grep -q "pass" "$CSV"; then
  echo "[ole-two-party] no validation column reported pass"
  exit 1
fi
echo "[ole-two-party] real OLE engine validates on two-party dealerless keys"
