#!/usr/bin/env bash
# Drives the real Figure 2 Ring-LPN OLE engine from independently sampled
# per-party noise and SPFSS keys generated by two OS processes. This is an
# artifact integration run, not a claim of DPF security, silent OT, or a full
# two-process FC composition.
#
# Two stages:
#   1. for each CRT limb, each keygen process samples only its own NoiseRecord
#      with its OS-backed private DRBG, persists that record as evidence, and
#      writes only its own SPFSS key file after the two-party protocol;
#   2. run the OLE bench once with both records and both key files, and require
#      the engine's own validation to pass.
#
# Outputs:
#   results/ole/ole_two_party_keys_<tag>.csv        (engine validation evidence)
#   results/ole/ole_two_party_keygen_<tag>.csv      (per-party transcript rows)
#   results/ole/ole_two_party_keys_<tag>.log
#   $WORKDIR/noise_limb*_p*.noise                   (per-party noise evidence)
#   $WORKDIR/keys_limb*_p*.spfss                    (matching per-party keys)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"
BENCH="$ROOT/bin/bench_ole_ringlpn_cuda"
KEYGEN="$ROOT/host_bin/test_two_party_spfss_keygen"
OUTDIR="$ROOT/results/ole"
N="${N:-8192}"
C="${C:-2}"
T="${T:-8}"
QBITS="${QBITS:-64}"
NOISE="${NOISE:-uniform}"
SEED="${SEED:-1}"
ITERS="${ITERS:-1}"
WARMUP="${WARMUP:-0}"
BASE_PORT="${BASE_PORT:-45600}"
SID="${SID:-$(date +%s%N)}"
TAG="q${QBITS}_${NOISE}_c${C}_t${T}_n${N}"
WORKDIR="${WORKDIR:-$OUTDIR/two_party_keys/$TAG}"
CSV="$OUTDIR/ole_two_party_keys_${TAG}.csv"
KCSV="$OUTDIR/ole_two_party_keygen_${TAG}.csv"
LOG="$OUTDIR/ole_two_party_keys_${TAG}.log"
CUDA_ARCH="${CUDA_ARCH:-${GPU_ARCH:-89}}"
NVCC="${NVCC:-nvcc}"

for name in N C T QBITS SEED ITERS WARMUP BASE_PORT SID; do
  value="${!name}"
  if [[ ! "$value" =~ ^[0-9]+$ ]]; then
    echo "[ole-two-party] $name must be an unsigned decimal integer"
    exit 1
  fi
done
case "$QBITS" in
  64) moduli=(4611686018326724609) ;;
  128) moduli=(4611686018326724609 4611686018309947393) ;;
  *) echo "[ole-two-party] QBITS must be 64 or 128"; exit 1 ;;
esac
limbs=${#moduli[@]}
if ((N < 8192 || N > 1048576 || (N & (N - 1)) != 0 ||
     C <= 0 || T <= 0 || T > N || C > 255 ||
     C * C > 65535 || ITERS <= 0)); then
  echo "[ole-two-party] unsupported N/C/T/ITERS public work parameters"
  exit 1
fi
if [[ "$NOISE" == regular ]]; then
  if ((N % T != 0 || (T & (T - 1)) != 0)); then
    echo "[ole-two-party] regular noise requires power-of-two T dividing N"
    exit 1
  fi
  spfss_domain=$((2 * (N / T)))
elif [[ "$NOISE" == uniform ]]; then
  spfss_domain=$((2 * N))
else
  echo "[ole-two-party] NOISE must be uniform or regular"
  exit 1
fi
log_domain=0
domain_cursor=$spfss_domain
while ((domain_cursor > 1 && domain_cursor % 2 == 0)); do
  domain_cursor=$((domain_cursor / 2))
  log_domain=$((log_domain + 1))
done
ct=$((C * T))
trees=$((ct * ct))
frontier_nodes=$((trees * spfss_domain))
cc_coeffs=$((C * C * N))
c_coeffs=$((C * N))
aggregate_words=$((12 * cc_coeffs + 8 * c_coeffs + 16 * N))
if ((domain_cursor != 1 || log_domain < 2 || log_domain > 20 ||
     trees <= 0 || trees > 16384 || frontier_nodes > 16777216 ||
     aggregate_words > 1073741824)); then
  echo "[ole-two-party] derived keygen/GPU work exceeds supported cap"
  exit 1
fi
if ((BASE_PORT <= 0 || BASE_PORT + 4 * limbs > 65534)); then
  echo "[ole-two-party] BASE_PORT does not leave valid main and rename-control ports"
  exit 1
fi

if ! command -v "$NVCC" >/dev/null 2>&1; then
  echo "[ole-two-party] nvcc not found; run inside the CUDA environment"
  exit 1
fi

mkdir -p "$OUTDIR" "$WORKDIR" "$ROOT/host_bin" "$ROOT/bin"
: > "$LOG"
rm -f "$CSV" "$KCSV"
# Stale per-party noise/key files from another configuration must never be
# consumed as evidence for this run.
rm -f "$WORKDIR"/noise_limb*.noise "$WORKDIR"/keys_limb*.spfss "$WORKDIR"/keygen_limb*_p*.csv
g++ -std=c++17 -O2 -Wall -Wextra -maes -msse4.1 -mpclmul -mavx2 -mrdseed \
  -I "$PROJECT_ROOT/../SCI/src" -I "$ROOT/src" \
  "$ROOT/src/test_two_party_spfss_keygen.cpp" "$ROOT/src/spfss_host.cpp" \
  -o "$KEYGEN" -lcrypto -lssl -pthread
"$ROOT/scripts/build_ole_cuda_bench.sh" >> "$LOG" 2>&1

bench_args=(--n "$N" --c "$C" --t "$T" --qbits "$QBITS" --noise "$NOISE"
            --seed "$SEED" --iters "$ITERS" --warmup "$WARMUP")

active_p0=
active_p1=
terminate_active() {
  for pid in "$active_p0" "$active_p1"; do
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      kill -TERM "$pid" 2>/dev/null || true
    fi
  done
  for pid in "$active_p0" "$active_p1"; do
    if [[ -n "$pid" ]]; then wait "$pid" 2>/dev/null || true; fi
  done
}
trap terminate_active EXIT INT TERM

wait_keygen_pair() {
  local p0="$1" p1="$2" finished first_rc remaining second_rc
  rc0=0
  rc1=0
  set +e
  wait -n -p finished "$p0" "$p1"
  first_rc=$?
  if [[ "$finished" == "$p0" ]]; then
    rc0=$first_rc
    remaining=$p1
  else
    rc1=$first_rc
    remaining=$p0
  fi
  if ((first_rc != 0)); then
    kill -TERM "$remaining" 2>/dev/null || true
  fi
  wait "$remaining"
  second_rc=$?
  set -e
  if [[ "$remaining" == "$p0" ]]; then rc0=$second_rc; else rc1=$second_rc; fi
}

echo "[ole-two-party] stage 1: independently sample per-party noise and generate keys for $limbs limb(s)" | tee -a "$LOG"
port=$BASE_PORT
header=1
status=0
for ((limb = 0; limb < limbs; ++limb)); do
  limb_sid=$((SID + limb))
  hdr=()
  if [[ $header -eq 1 ]]; then hdr=(--csv-header); header=0; fi
  p0_csv="$WORKDIR/keygen_limb${limb}_p0.csv"
  p1_csv="$WORKDIR/keygen_limb${limb}_p1.csv"
  timeout --signal=TERM --kill-after=5s 300s \
    "$KEYGEN" --party 0 --port "$port" --sample-independent \
              --sid "$limb_sid" \
              --c "$C" --t "$T" --log-domain "$log_domain" \
              --modulus "${moduli[$limb]}" --noise-mode "$NOISE" \
              --noise "$WORKDIR/noise_limb${limb}_p0.noise" \
              --out "$WORKDIR/keys_limb${limb}_p0.spfss" "${hdr[@]}" \
              > "$p0_csv" 2>> "$LOG" &
  p0=$!
  sleep 0.2
  timeout --signal=TERM --kill-after=5s 300s \
    "$KEYGEN" --party 1 --host 127.0.0.1 --port "$port" --sample-independent \
              --sid "$limb_sid" \
              --c "$C" --t "$T" --log-domain "$log_domain" \
              --modulus "${moduli[$limb]}" --noise-mode "$NOISE" \
              --noise "$WORKDIR/noise_limb${limb}_p1.noise" \
              --out "$WORKDIR/keys_limb${limb}_p1.spfss" \
              > "$p1_csv" 2>> "$LOG" &
  p1=$!
  active_p0=$p0
  active_p1=$p1
  wait_keygen_pair "$p0" "$p1"
  active_p0=
  active_p1=
  cat "$p0_csv" "$p1_csv" >> "$KCSV"
  if [[ $rc0 -ne 0 || $rc1 -ne 0 ]]; then
    echo "[ole-two-party] keygen FAILED (p0=$rc0 p1=$rc1) limb $limb" | tee -a "$LOG"
    status=1
  fi
  port=$((port + 4))
done
python3 - "$KCSV" "$limbs" <<'PY'
import csv
import sys

path, expected_limbs = sys.argv[1], int(sys.argv[2])
with open(path, newline="", encoding="utf-8") as handle:
    rows = list(csv.DictReader(handle))
if len(rows) != 2 * expected_limbs:
    raise SystemExit(f"expected {2 * expected_limbs} keygen rows, got {len(rows)}")
by_sid = {}
for row in rows:
    if row["noise_source"] != "independent_os_drbg":
        raise SystemExit("non-independent noise source in live keygen evidence")
    if row["status"] != "pass" or row["transcript_accounting"] != "pass":
        raise SystemExit("failed keygen/protocol accounting row")
    sid = int(row["sid"])
    if sid == 0:
        raise SystemExit("zero SPFSS session id")
    by_sid.setdefault(sid, []).append(row)
if len(by_sid) != expected_limbs:
    raise SystemExit("session-id count does not match CRT limbs")
for sid, pair in by_sid.items():
    if sorted(int(row["party"]) for row in pair) != [0, 1]:
        raise SystemExit(f"session {sid} does not contain exactly parties 0 and 1")
    if pair[0]["public_manifest_sha256"] != pair[1]["public_manifest_sha256"]:
        raise SystemExit(f"session {sid} public manifest digest mismatch")
    if pair[0]["common_cw_sha256"] != pair[1]["common_cw_sha256"]:
        raise SystemExit(f"session {sid} common-CW transcript digest mismatch")
    if pair[0]["noise_content_sha256"] == pair[1]["noise_content_sha256"]:
        raise SystemExit(f"session {sid} noise term content is identical")
print("[ole-two-party] provenance binds each independent-noise/key pair")
PY

# Transactional publication control: make party 0's final key path a non-empty
# directory so its rename fails after both parties stage successfully. Both
# processes must report failure, and party 1 must remove its already-renamed
# key/noise files after receiving party 0's rename result.
rename_port=$((BASE_PORT + 4 * limbs))
rename_dir="$WORKDIR/rename_failure_p0.spfss"
rename_p1="$WORKDIR/rename_failure_p1.spfss"
rename_noise0="$WORKDIR/rename_failure_p0.noise"
rename_noise1="$WORKDIR/rename_failure_p1.noise"
rm -rf "$rename_dir"
rm -f "$rename_p1" "$rename_noise0" "$rename_noise1" \
      "$rename_dir.tmp" "$rename_p1.tmp" "$rename_noise0.tmp" "$rename_noise1.tmp"
mkdir -p "$rename_dir"
printf 'force rename failure\n' >"$rename_dir/blocker"
"$KEYGEN" --party 0 --port "$rename_port" --sample-independent \
          --sid "$((SID + limbs + 1000))" --c 1 --t 1 --log-domain 14 \
          --modulus "${moduli[0]}" --noise-mode uniform \
          --noise "$rename_noise0" --out "$rename_dir" \
          >"$WORKDIR/rename_failure_p0.csv" 2>>"$LOG" &
rename_p0=$!
sleep 0.2
"$KEYGEN" --party 1 --host 127.0.0.1 --port "$rename_port" \
          --sample-independent --sid "$((SID + limbs + 1000))" \
          --c 1 --t 1 --log-domain 14 --modulus "${moduli[0]}" \
          --noise-mode uniform --noise "$rename_noise1" --out "$rename_p1" \
          >"$WORKDIR/rename_failure_p1.csv" 2>>"$LOG" &
rename_p1_pid=$!
set +e
wait "$rename_p0"; rename_rc0=$?
wait "$rename_p1_pid"; rename_rc1=$?
set -e
if [[ $rename_rc0 -ne 1 || $rename_rc1 -ne 1 || -e "$rename_p1" ||
      -e "$rename_noise0" || -e "$rename_noise1" ||
      -e "$rename_dir.tmp" || -e "$rename_p1.tmp" ||
      -e "$rename_noise0.tmp" || -e "$rename_noise1.tmp" ]]; then
  echo "[ole-two-party] bilateral rename-failure control FAILED (p0=$rename_rc0 p1=$rename_rc1)" | tee -a "$LOG"
  exit 1
fi
rm -rf "$rename_dir"
echo "[ole-two-party] bilateral rename failure removed both parties' staged/final records" >>"$LOG"

echo "[ole-two-party] stage 2: OLE engine consumes independently sampled noise and matching keys" | tee -a "$LOG"
if ! RINGLPN_OLE_NOISE="$WORKDIR/noise" \
      RINGLPN_OLE_SPFSS_KEYS="$WORKDIR/keys" \
      "$BENCH" "${bench_args[@]}" --csv-header > "$CSV" 2>> "$LOG"; then
  echo "[ole-two-party] bench FAILED on independently sampled noise and matching keys" | tee -a "$LOG"
  status=1
fi
cat "$CSV" >> "$LOG"

echo "wrote $CSV"
echo "wrote $KCSV"
echo "wrote $LOG"
echo "kept independently sampled per-party noise and matching keys in $WORKDIR"
if [[ $status -ne 0 ]] || grep -qi "fail" "$CSV" || grep -qi "FAIL" "$KCSV"; then
  echo "[ole-two-party] FAILURES present"
  exit 1
fi
if ! grep -q "pass" "$CSV"; then
  echo "[ole-two-party] no validation column reported pass"
  exit 1
fi
echo "[ole-two-party] real OLE engine validates on independently sampled per-party noise and matching two-party keys"
